### ISSUE TITLE
Question : How to use promises with machine ?

### ISSUE THREAD

**Issue by Aurelsicoko** [node-machine/machine#3]
Hi!

The approach of thinking with the machines is very cool, but how to use promises with machines? What's the best way to do it ? 

Is machinepack-loop replaces Q.all([]) ?

Thx

**Comment by sgress454** [comment]
Machines aren't directly compatible with promise libraries like Bluebird or Q, because those libraries are still based on the paradigm of a function having only two possible outcomes:  success or failure.  Machines can have as many *exits* as there are possible outcomes.  For example, a machine that makes an API call might have "success", "apiUnavailable", "rateLimitExceeded", etc.  So rather than using a single "catch" and trying to determine why your request wasn't successful, you have a declarative way of handling every possible result.

The `machinepack-loop` machines allow you to emulate something like `Array.map(myArray, myFunc)` but replacing `myFunc` with a machine!  They're still in development but the possibilities for automation are pretty exciting.
