### ISSUE TITLE
Input field mutates the Object.

### ISSUE THREAD

**Issue by raghavgarg1257** [node-machine/machine#42]
I am using Sails v1 and in its [helper](http://next.sailsjs.com/documentation/concepts/helpers) it is using node-machine type function. Sails v1 suggest using the helpers for defining defaults value for the model fields. Now, `inputs` field of machine function takes the same field as the model, so I was trying to define a single file and use it in both places, helpers and models.
But helper is mutating my file in some way, that I am unable to use the same file for models.

```js
// userTraits.js (single schema file)
module.exports = {
    email: {
        type: 'string',
        required: true
    },
    referral_key: {
        type: 'string',
    }
};
```
```js
// user-helper.js (helper file: node-machine function)
const shortid = require('shortid');
const userTraits = require('./userTraits');
module.exports = {
    friendlyName: 'Create user',
    description: '',
    inputs: Object.assign({}, userTraits, {
        referral_key: {
            type: 'string',
            defaultsTo: shortid.generate()
        }
    }),
    fn: function(inputs, exit) {
        // some logic
        return exit.success();
    }
}
```
```js
// Users.js (user model to interact with db using waterline ORM)
const userTraits = require('./userTraits');
modules.exports = {
    attributes: Object.assign({}, userTrait) 
    // but this doesn't give me the object from user trait, it gives the mutated object
    /*
        {
            email: { required: true, example: 'a string', _id: 'first_name' },
            referral_key: { example: 'a string', _id: 'referral_key' } 
        }
    */
}
```
**Note**: In sails, helpers are executed before the models.

The machine is mutating the object rather it should make an immutable copy of it and work on it. If I am wrong somewhere, please correct me.

**Comment by mikermcneil** [comment]
Hey @raghavgarg1257, thanks for the detailed write-up!  This is one of the balances we're trying to reach across the board in Sails v1-- between mutating stuff in-place and deep-cloning.  In the past, we would always deep-clone before changing stuff to avoid causing problems in userland code.  But in Sails v1, we did a lot of work optimizing pieces that were historically slow, and found that this cloning was causing an inordinate amount of latency/CPU load.  Thus, we've been mutating stuff in-place in some cases where we didn't in the past.

That said, it's probably safe to change that approach here, since building helpers is a 1-time thing that happens on load (rather than a per-request thing).  The right place to do that is probably in machine-as-action, somewhere just _before_ we do [this](https://github.com/sailshq/machine-as-action/blob/b9ac31ffa69ed947242b01f8134d8940823399a1/index.js#L245-L249).

**Comment by raghavgarg1257** [comment]
Thanks for the reply, the suggestion you gave seems likely to work but I have downgraded from sails v1 to v0.10. Although the v1 looks promising but there were too many structural changes compared to v0.10. I think I will wait for it to get more mature.
